#!/usr/bin/env python3
"""Turn the gitignored tenant-config/ extract into a committable structural summary.

The rule: counts, shapes and process names. NOT group names, agent names, support
addresses, macro/view/trigger titles, webhook endpoints or installed apps - those
are CSA infrastructure detail and this repo goes public.

Ticket-field and form titles ARE included in the generated summary, because the
required-to-solve matrix is useless without them - which is precisely why the
generated summary is written into the GITIGNORED tenant-config/ directory and is
never committed. This script produces private output by design.
"""
from __future__ import annotations

import collections
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CFG = ROOT / "tenant-config"


def load(name):
    p = CFG / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else None


def main() -> int:
    fields = {f["id"]: f for f in (load("ticket_fields") or [])}
    forms = load("ticket_forms") or []
    L = []
    w = L.append

    w("# CSA Zendesk — tenant configuration\n")
    w("Structural summary of the configuration extract, generated by")
    w("`scripts/summarise_config.py` from `scripts/extract_config.py` output.\n")
    w("The extract itself is **not committed** — it holds group structure, support")
    w("addresses, trigger rules, webhook endpoints and installed apps. This file is")
    w("counts, shapes and process names only.\n")
    w("> This describes **CSA's** Zendesk, not Zendesk in general. Every count below is")
    w("> account configuration that an admin can change without notice.\n")

    idx = load("_index") or {}
    w("## Scale\n")
    w("| Object | Count | Note |")
    w("|---|---:|---|")
    ORDER = [("ticket_fields","ticket fields"),("ticket_forms","ticket forms"),
             ("custom_statuses","custom statuses"),("groups","groups"),
             ("custom_roles","custom roles"),("macros","macros"),
             ("triggers","triggers"),("trigger_categories","trigger categories"),
             ("automations","automations"),("views","views"),
             ("sla_policies","SLA policies"),("webhooks","webhooks"),
             ("apps_installed","installed apps"),("tags","tags"),
             ("support_addresses","support addresses"),("brands","brands"),
             ("organization_fields","organization fields"),("user_fields","user fields"),
             ("custom_objects","custom objects"),("dynamic_content","dynamic content items"),
             ("routing_attributes","routing attributes"),("queues","omnichannel queues"),
             ("hc_categories","Help Center categories"),("hc_sections","Help Center sections"),
             ("hc_user_segments","Help Center user segments")]
    for key, label in ORDER:
        e = idx.get(key) or {}
        c = e.get("count", "—")
        note = "" if str(e.get("note","")).startswith("ok") else str(e.get("note",""))[:60]
        w(f"| {label} | {c} | {note} |")

    w("\n### Empty — configured-but-unused, or unavailable\n")
    empties = [l for k, l in ORDER if (idx.get(k) or {}).get("count") == 0]
    w(", ".join(empties) + ".\n")
    w("**No SLA policies exist.** Catherine's March 2026 analysis proposed implementing a")
    w("tiered SLA as action 12; the extract confirms it has not happened. Any tool")
    w("surfacing SLA breach data would today return nothing.\n")
    for k in ("group_sla_policies", "ticket_form_statuses"):
        e = idx.get(k) or {}
        if str(e.get("note","")).startswith("HTTP"):
            w(f"`{k}` — **{str(e['note'])[:20].strip()}**, plan or feature gated on this account.\n")

    w("## Ticket fields\n")
    types = collections.Counter(f["type"] for f in fields.values())
    w("| Type | Count |")
    w("|---|---:|")
    for t, c in types.most_common():
        w(f"| `{t}` | {c} |")
    act = sum(1 for f in fields.values() if f.get("active"))
    req = sum(1 for f in fields.values() if f.get("required"))
    reqa = sum(1 for f in fields.values() if f.get("required") and f.get("active"))
    w(f"\n{len(fields)} fields total · {act} active · {req} flagged required-to-solve "
      f"({reqa} of them active).\n")

    w("## Forms, and what each needs to reach `solved`\n")
    w("This is the answer to *“what does a ticket need to be closed?”*, per form.")
    w("Computed from `ticket_fields[].required` scoped to the form's own fields, plus")
    w("`ticket_forms[].agent_conditions[]`.\n")
    w("> **Known limitation — the conditional forms over-report.** The model was verified")
    w("> against a live 422 on *IT Requests*, which has **zero** conditional rules, so the")
    w("> match validated only the unconditional half. On a form with conditions it is")
    w("> visibly wrong: the QMS form below lists both `CAR1 - Corrective Actions")
    w("> Description` (the `yes` branch) and `Non-action Justification` (the `no` branch)")
    w("> as always-required, and those are mutually exclusive. The global `required` flag")
    w("> is evidently **subordinate to field visibility** — a field counts as required only")
    w("> when the form's conditions surface it. Until that is confirmed against a real QMS")
    w("> ticket, treat the conditional forms' \"always required\" lists as a superset, and")
    w("> the 422 as the authority.\n")
    for form in sorted(forms, key=lambda f: (not f.get("active"), f.get("name",""))):
        ids = form.get("ticket_field_ids") or []
        always = [fields[i]["title"].strip() for i in ids
                  if i in fields and fields[i].get("required") and fields[i].get("active")]
        conds = form.get("agent_conditions") or []
        w(f"### {form.get('name')}"
          f"{'' if form.get('active') else '  *(inactive)*'}"
          f"{'  — default' if form.get('default') else ''}\n")
        w(f"{len(ids)} fields · {len(conds)} conditional rule(s)\n")
        if always:
            w("Always required to solve:\n")
            for t in sorted(always):
                w(f"- {t}")
            w("")
        for c in conds:
            parent = fields.get(c.get("parent_field_id"), {}).get("title", "?").strip()
            kids = []
            for ch in c.get("child_fields") or []:
                ros = ch.get("required_on_statuses") or {}
                if ch.get("is_required"):
                    on = ros.get("type") if ros.get("type") == "ALL_STATUSES" else \
                         "/".join(ros.get("statuses") or ["?"])
                    kids.append(f"{fields.get(ch['id'],{}).get('title','?').strip()} (on {on})")
            if kids:
                w(f"If **{parent}** = `{c.get('value')}` → also required:\n")
                for k in kids:
                    w(f"- {k}")
                w("")
        if not always and not conds:
            w("_Nothing blocks solve on this form._\n")

    w("## Statuses\n")
    st = load("custom_statuses") or []
    w("| Category | Agent label | Default | Active |")
    w("|---|---|---|---|")
    for s in st:
        w(f"| `{s['status_category']}` | {s['agent_label']} | {s['default']} | {s['active']} |")
    w("\nAll five are Zendesk built-ins — **no custom statuses have been defined**, which is")
    w("why `ticket_form_statuses` has nothing to return. There is no `closed`: a ticket")
    w("reaches Closed by automation some days after Solved, never by an agent action.\n")

    w("## Rule engine\n")
    for key, label in (("macros","Macros"),("triggers","Triggers"),
                       ("automations","Automations"),("views","Views")):
        items = load(key) or []
        if not items:
            continue
        active = sum(1 for i in items if i.get("active"))
        w(f"- **{label}:** {len(items)} total, {active} active, {len(items)-active} inactive")
    w("")
    w("A large macro and view estate is a body of encoded institutional practice. Any tool")
    w("that lets a model *apply* a macro invokes a rule someone wrote years ago;")
    w("`list_macros` should surface enough for a caller to know what one does before applying it.\n")

    (ROOT / "tenant-config/SUMMARY.md").write_text("\n".join(L) + "\n")
    print(f"-> tenant-config/SUMMARY.md ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
